version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: vvakame/circleci-gaego
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          DISPLAY: ":99"
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-front2-{{ checksum "front2/package-lock.json" }}

      # setup
      - run: gcloud --quiet components update --version 162.0.1
      - run: rm -rf /work/go_appengine
      - run: curl -o /work/go_appengine_sdk_linux_amd64.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.55.zip
      - run: unzip -q -d /work /work/go_appengine_sdk_linux_amd64.zip

      # dependencies
      - run:
          name: install api dependencies
          command: ./setup.sh
          working_directory: ./api
      - run:
          name: install front dependencies
          command: npm install --no-save
          working_directory: ./front2
      - save_cache:
          key: npm-cache-front2-{{ checksum "front2/package-lock.json" }}
          paths:
            - ./front2/node_modules

      # test
      - run:
          name: running api test
          command: ./test.sh
          working_directory: ./api
      - run:
          name: running front test
          command: |
            npm run build:prod
            npm run swagger-ui
            xvfb-run npm run test
          working_directory: ./front2

      - deploy:
          name: Deploy to GAE
          command: |
            case "${CIRCLE_BRANCH}" in
              "master" )
                (cd ./front2 && npm run build:prod)
                (cd ./api && ./deploy.sh) ;;
            esac

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
