version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: vvakame/circleci-gaego
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          DISPLAY: ":99"
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "front/yarn.lock" }}
      - run: npm install -g yarn

      # api
      - run: rm -rf /work/go_appengine
      - run: curl -o /work/go_appengine_sdk_linux_amd64.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.58.zip
      - run: unzip -q -d /work /work/go_appengine_sdk_linux_amd64.zip
      - run:
          name: setup GAE/Go dependencies
          command: ./setup.sh
          working_directory: ./api
      # front
      - run:
          command: yarn install
          working_directory: ./front
      # caching
      - save_cache:
          key: yarn-cache-{{ checksum "front/yarn.lock" }}
          paths:
            # `yarn cache dir`
            - /usr/local/share/.cache/yarn/v1
      # test
      - run:
          name: run GAE/Go test
          command: ./test.sh
          working_directory: ./api
      - run:
          name: running front test
          command: |
            npm run build:prod
            npm run swagger-ui
            xvfb-run npm run test
          working_directory: ./front
      - deploy:
          name: Deploy to GAE
          command: |
            case "${CIRCLE_BRANCH}" in
              "master" )
                (cd ./front && npm run build:prod)
                (cd ./api && ./deploy.sh) ;;
            esac
